extends CanvasLayer

@onready var back_button: SoundButton = %BackButton


func _ready() -> void:
    back_button.pressed.connect(on_back_button_pressed)

    back_button.hide()
    Narrator.add_message("YOU DID IT.")
    Narrator.add_message("THANK YOU.")
    Narrator.add_message("<3")

    await Narrator.messages_empty
    back_button.show()

    await get_tree().create_timer(15).timeout
    Narrator.add_message("SOMEBODY ONCE TOLD ME.")
    Narrator.add_message("THE WORLD IS GONNA ROLL ME.")
    Narrator.add_message("I AINT THE SHARPEST TOOL IN THE SHED.")
    Narrator.add_message("SHE WAS LOOKING KIND OF DUMB.")
    Narrator.add_message("WITH HER FINGER AND HER THUMB.")
    Narrator.add_message("IN THE SHAPE OF AN L ON HER FOREHEAD.")
    Narrator.add_message("WELL THE YEARS START COMIN.")
    Narrator.add_message("AND THEY DONT STOP COMIN.")
    Narrator.add_message("FED TO THE RULES.")
    Narrator.add_message("AND I HIT THE GROUND RUNNIN.")
    Narrator.add_message("DIDNT MAKE SENSE NOT TO LIVE FOR FUN.")
    Narrator.add_message("YOUR BRAIN GETS SMART.")
    Narrator.add_message("BUT YOUR HEAD GETS DUMB.")
    Narrator.add_message("SO MUCH TO DO SO MUCH TO SEE.")
    Narrator.add_message("SO WHATS WRONG WITH TAKING THE BACKSTREETS.")
    Narrator.add_message("YOULL NEVER KNOW IF YOU DONT GO.")
    Narrator.add_message("YOULL NEVER SHINE IF YOU DONT GLOW.")
    Narrator.add_message("HEY NOW YOURE AN ALL STAR.")
    Narrator.add_message("GET YOUR GAME ON GO PLAY.")
    Narrator.add_message("HEY NOW YOURE A ROCK STAR.")
    Narrator.add_message("GET THE SHOW ON GET PAID.")
    Narrator.add_message("AND ALL THAT GLITTERS IS GOLD.")
    Narrator.add_message("ONLY SHOOTIN STARS BREAK THE MOLD.")
    Narrator.add_message("ITS A COOL PLACE.")
    Narrator.add_message("AND THEY SAY IT GETS COLDER.")
    Narrator.add_message("YOURE BUNDLED UP NOW.")
    Narrator.add_message("WAIT TIL YOU GET OLDER.")
    Narrator.add_message("BUT THE METEOR MEN BEG TO DIFFER.")
    Narrator.add_message("JUDGING BY THE HOLE IN THE SATELLITE PICTURE.")
    Narrator.add_message("THE ICE WE SKATE IS GETTIN PRETTY THIN.")
    Narrator.add_message("THE WATERS GETTIN WARM.")
    Narrator.add_message("SO YOU MIGHT AS WELL SWIM.")
    Narrator.add_message("MY WORLDS ON FIRE.")
    Narrator.add_message("HOW BOUT YOURS.")
    Narrator.add_message("THATS THE WAY I LIKE IT.")
    Narrator.add_message("AND ILL NEVER GET BORED.")
    Narrator.add_message("HEY NOW YOURE AN ALL STAR.")
    Narrator.add_message("GET YOUR GAME ON GO PLAY.")
    Narrator.add_message("HEY NOW YOURE A ROCK STAR.")
    Narrator.add_message("GET THE SHOW ON GET PAID.")
    Narrator.add_message("AND ALL THAT GLITTERS IS GOLD.")
    Narrator.add_message("ONLY SHOOTIN STARS BREAK THE MOLD.")
    Narrator.add_message("HEY NOW YOURE AN ALL STAR.")
    Narrator.add_message("GET YOUR GAME ON GO PLAY.")
    Narrator.add_message("HEY NOW YOURE A ROCK STAR.")
    Narrator.add_message("GET THE SHOW ON GET PAID.")
    Narrator.add_message("AND ALL THAT GLITTERS IS GOLD.")
    Narrator.add_message("ONLY SHOOTIN STARS.")
    Narrator.add_message("SOMEBODY ONCE ASKED.")
    Narrator.add_message("COULD I SPARE SOME CHANGE FOR GAS.")
    Narrator.add_message("I NEED TO GET MYSELF AWAY FROM THIS PLACE.")
    Narrator.add_message("I SAID YEP WHAT A CONCEPT.")
    Narrator.add_message("I COULD USE A LITTLE FUEL MYSELF.")
    Narrator.add_message("AND WE COULD ALL USE A LITTLE CHANGE.")
    Narrator.add_message("WELL THE YEARS START COMIN.")
    Narrator.add_message("AND THEY DONT STOP COMIN.")
    Narrator.add_message("FED TO THE RULES AND I HIT THE GROUND RUNNIN.")
    Narrator.add_message("DIDNT MAKE SENSE NOT TO LIVE FOR FUN.")
    Narrator.add_message("YOUR BRAIN GETS SMART.")
    Narrator.add_message("BUT YOUR HEAD GETS DUMB.")
    Narrator.add_message("SO MUCH TO DO SO MUCH TO SEE.")
    Narrator.add_message("SO WHATS WRONG WITH TAKING THE BACKSTREETS.")
    Narrator.add_message("YOULL NEVER KNOW IF YOU DONT GO.")
    Narrator.add_message("YOULL NEVER SHINE IF YOU DONT GLOW.")
    Narrator.add_message("HEY NOW YOURE AN ALL STAR.")
    Narrator.add_message("GET YOUR GAME ON GO PLAY.")
    Narrator.add_message("HEY NOW YOURE A ROCK STAR.")
    Narrator.add_message("GET THE SHOW ON GET PAID.")
    Narrator.add_message("AND ALL THAT GLITTERS IS GOLD.")
    Narrator.add_message("ONLY SHOOTIN STARS BREAK THE MOLD.")
    Narrator.add_message("ONLY SHOOTIN STARS BREAK THE MOLD.")


func on_back_button_pressed() -> void:
    Transition.transition()
    await Transition.obscuring
    Narrator.reset()
    get_tree().change_scene_to_file("res://scenes/ui/menus/main_menu.tscn")
